export const MASTER_PERMISSIONS = [
  { action: "org.read", description: "View organization details" },
  { action: "org.update", description: "Update organization details" },
  { action: "org.delete", description: "Delete organization (Owner only)" },
  { action: "users.read", description: "View organization members" },
  { action: "users.invite", description: "Invite new team members" },
  { action: "users.remove", description: "Remove team members" },
  { action: "users.role.update", description: "Update team member roles" },
  { action: "projects.read", description: "View projects" },
  { action: "projects.write", description: "Create and update projects" },
  { action: "billing.read", description: "View billing information" },
  { action: "billing.update", description: "Update billing and subscription (Owner only)" },
  { action: "audit_logs.read", description: "View organization audit logs" },
  { action: "apikeys.read", description: "View API Keys" },
  { action: "apikeys.create", description: "Create API Keys" },
  { action: "apikeys.delete", description: "Delete API Keys" },
];

export const ROLE_PERMISSIONS_MAP: Record<string, string[]> = {
  owner: [
    "org.read",
    "org.update",
    "org.delete",
    "users.read",
    "users.invite",
    "users.remove",
    "users.role.update",
    "projects.read",
    "projects.write",
    "billing.read",
    "billing.update",
    "audit_logs.read",
    "apikeys.read",
    "apikeys.create",
    "apikeys.delete",
  ],
  admin: [
    "org.read",
    "org.update",
    "users.read",
    "users.invite",
    "users.remove",
    "users.role.update",
    "projects.read",
    "projects.write",
    "billing.read",
    "audit_logs.read",
    "apikeys.read",
  ],
  member: ["org.read", "users.read", "projects.read", "projects.write"],
  viewer: ["org.read", "users.read", "projects.read"],
};
